import Image from "next/image";
import Hero from "./organisms/Hero";
import Services from "./organisms/Services";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function Home() {
	return (
		<main className="flex min-h-screen flex-col items-center justify-between p-24 pt-0 md:pt-16">
			<Hero />
			<Services />
		</main>
	);
}
